env: "local"
server:
  host: "0.0.0.0"
  port: "4400"
  timeout: 10s
storage:
  host: "events-planning-events-postgres"
  port: "5432"
  username: "sleeps17"
  password: "Pavel19122004"
  database: "events-service"
  timeout: 20s
