version: '3.9'

services:
  events-planning-rooms-postgres:
    image: postgres:latest
    container_name: events-planning-rooms-postgres
    restart: always
    environment:
      - POSTGRES_USER=sleeps17
      - POSTGRES_PASSWORD=Pavel19122004
      - POSTGRES_DB=rooms-service
    ports:
      - "5434:5432"
    volumes:
      - "rooms_data:/var/lib/postgresql/data"

  events-planning-rooms-service:
    build: .
    container_name: events-planning-rooms-service
    restart: always
    environment:
      DATABASE_URL: postgres://sleeps17:Pavel19122004@events-planning-rooms-postgres:5432/rooms-service
    ports:
      - "4404:4404"
    depends_on:
      - events-planning-rooms-postgres

volumes:
  rooms_data: {}