env: "local"
server:
  host: "0.0.0.0"
  port: "4404"
  timeout: 10s
storage:
  host: "events-planning-rooms-postgres"
  port: "5432"
  username: "sleeps17"
  password: "Pavel19122004"
  database: "rooms-service"
  timeout: 20s
