version: '3'

tasks:
  clear:
    cmds:
      - rm -rf ./gen/go/*
  gen-employees:
    cmds:
      - find ./proto/employees -name "*.proto" | xargs protoc -I proto -I ~/protobuf/src -I ./proto/employees --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative