version: '3'

tasks:
  clear:
    cmds:
      - rm -rf ./gen/go/*
  gen-auth:
    cmds:
      - find ./proto/auth -name "*.proto" | xargs protoc -I proto -I ./proto/auth --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
  gen-employees:
    cmds:
      - find ./proto/employees -name "*.proto" | xargs protoc -I proto -I ./proto/employees --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
  gen-events:
    cmds:
      - find ./proto/events -name "*.proto" | xargs protoc -I proto -I ./proto/events --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
  gen-rooms:
    cmds:
      - find ./proto/rooms -name "*.proto" | xargs protoc -I proto -I ./proto/rooms --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
  gen-all:
    cmds:
      - task gen-auth
      - task gen-employees
      - task gen-events
      - task gen-rooms